name: online-store-ci
run-name: ${{github.actor}}-${{github.action}}-${{github.event.repository.updated_at}}
on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        name: Setup dotnet 7
      - uses: actions/setup-dotnet@v3
        with:
          dotnet-version: 7.0.x
      - run: dotnet restore
        name: Restore project
        working-directory: Backend
      - run: dotnet build --configuration Release --no-restore
        name: Build Project
        working-directory: Backend
      - run: dotnet publish --configuration Release OnlineStore.Api
        name: Publish project OnlineStore.Api
        working-directory: Backend
      - name: Upload WebApp1 Build Artifact
        uses: actions/upload-artifact@v2
        with:
          name: OnlineStore
          path: /home/runner/work/OnlineStore/OnlineStore/Backend/OnlineStore.Api/bin/Release/net7.0/publish/
