name: online-store-ci
run-name: ${{github.actor}}
on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        name: Setup dotnet 7
      - run: dotnet build
        working-directory: Backend
